# Generated by Django 5.1.3 on 2024-11-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('type_product', models.CharField(max_length=40)),
                ('descriptions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry', models.CharField(max_length=40)),
            ],
        ),
    ]
